services:
  goverse-frontend:
    build: .
    container_name: goverse-frontend
    ports:
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
